@startuml
skinparam packageStyle rectangle

package "Model" {

  [Game] --> [Board]
  [Game] --> [Tetromino]
  [Game] --> [PieceQueue]
  [Game] --> [HoldSystem]
  [Game] --> [ScoreSystem]
  [Game] --> [LevelSystem]
  [Game] --> [GameplayRules]
  [Game] --> [GameTimer]
  [Game] --> [RandomBagGenerator]

  [GameplayRules] --> [Board]
  [GameplayRules] --> [Tetromino]

  [Board] --> [Cell]
  [Tetromino] --> [TetrominoType]
}

@enduml