@startuml
skinparam packageStyle rectangle

package "model" {

  package "board"
  package "tetromino"
  package "game"
  package "queue"
  package "hold"
  package "score"
  package "level"
  package "rules"
  package "random"
  package "timer"
  package "statistics"
  package "highscore"
  package "settings"
  package "types"
}

package "interfaces"

@enduml